### ISSUE TITLE
Unable to import fMsg.frm

### ISSUE THREAD

**Issue by Jonnie-Cache** [warbe-maker/VBA-Error#27]
When I try to import fMsg.frm into VBA, it imports the .frm into Modules instead of it being recognized as a form. I'm running VBA 7.1.

**Comment by warbe-maker** [comment]
You will have to download 3 files: 
fMsg.frm, 
fMsg frx, 
and mMsg.bas, 
The first two! into the same directory!

I will check if the README is clear enough regarding this point.

Regards
Walter
-- 
 Versendet mit Tuta. Hol dir sichere und werbefreie E-Mails: 
 https://tuta.com


21. Nov. 2023, 17:49 von ***@***.***:

**Comment by Jonnie-Cache** [comment]
Hi, @warbe-maker. Yes, I downloaded all 3 files into the same folder. The .bas (expected) and .frm (not expected) files imported both as Modules for some reason.

**Comment by warbe-maker** [comment]
What do you mean with "expected"? I assume you mean: the .bas file got imported as expected. Do the files have the correct extension .frm, .frx? I will try it by myself. In the meantime, as an alternative you may download the whole Workbook. In the VB-editor you then just drag and drop the fMsg and the mMsg.

**Comment by Jonnie-Cache** [comment]
@warbe-maker yes, the .bas file imports as a module as expected, but the .frm imports as a module also even though the frx is in the same folder.

I'm using VBA in Autodesk Inventor, so maybe that's why it isn't working. As far as I know, it's standard VBA 7.1.

I'll try the workbook to see if I can possibly export the frm from there to import into Inventor. I won't be able to try it until this weekend, but I'll let you know either way.

**Comment by warbe-maker** [comment]
The issue will be closed due to no response
